# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aleksey Fadeev
title: Senior ML Engineer
email: aleksei_fadeev@yahoo.com
website: https://github.com/AlekseyFadeev

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  AlekseyFadeev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aleksey-fadeev-8951b8189
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
## - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  A mathematician with strong theoretical background and practical experience in mathematical modeling, optimization and ML applications. I am currently leading the project on segmentation of remote sensing data.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Saint Petersburg State University
        caption: 2012 - 2017
        sub_title: M.Sc. jointly with B.Sc. in Mathematics, Department of Mathematics and Mechanics, Division of Geometry
        description: | # this will include new lines to allow paragraphs
          During my study I was working on theoretical questions in the field of dynamical systems with professor S.Yu. Pilyugin.
          I have obtained a new result for dynamical systems generated by special group actions.

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        caption: 2018
        sub_title: Fadeev A. V. Inverse shadowing in actions of Baumslag—Solitar group. Vestnik
          of Saint Petersburg University. Mathematics. Mechanics. Astronomy, 2018, vol. 5 (63), issue 4,
          pp. 637–644. https://doi.org/10.21638/11701/spbu01.2018.410 (In Russian).

  - title: Invited Talks
    layout: list
    content:
      - layout: top-middle
        caption: November 2016
        sub_title: Inverse shadowing in actions of Baumslag—Solitar group, Dynamical Systems Seminar, Freie Universität Berlin, Germany


  - title: Experience
    layout: list
    content:
      - layout: left
        title: Numerical Design
        link: https://numdes.com
        sub_title: Team Lead ML engineer
        caption: December 2019 - Present
        description: |
          I lead a work of ML team of 5 researchers / engineers. My key tasks include curating all the team members by suggesting new solutions and code reviewing.
          I develop our main code repository and solve the most difficult parts of our problems.
          From business point of view I play the role of translator from business language into mathematicaly correct tasks.
          Me and my team create algorithms for remote sensing data segmentation combining domain research and modern deep learning techniques.

      - layout: left
        title: Northern Capital Gateway LLC
        link: https://pulkovoairport.ru
        sub_title: Senior Data Analyst
        caption: November 2017 - July 2019
        description: |
          Created mathematical models for prediction of passenger traffic and airport capacity based on self-developed queue simulation tool.
          Also I integrated into airport data system my algorithm which automatically allocates parking stands for aircrafts on daily basis. This algorithm is still in use at Saint Petersburg airport.

      - layout: left
        title: Laboratory of Continuous Mathematical Education
        link: https://lnmo.ru
        sub_title: Math teacher
        caption: July 2014 - September 2015, January 2020 - March 2020
        description: |
          Led the work of the seminars on topology, geometry and ML for high school students.

  - title: My interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in theory and practice of ML:
      - Accordion and organ playing & [music composing](https://soundcloud.com/user-677381353)
      - Game development on Unity
      - 3D modeling

  - title: Detailed description of projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Semantic Segmentation of Remote Sensing Data
        # link_text: Project Website
        additional_links:
          - title: Habr
            icon: fas fa-book
            url: https://habr.com/ru/company/numdes/blog/575362/
          - title:  NumDes
            icon: fas fa-link
            url: https://numdes.com/
        description: | # this will include new lines to allow paragraphs
          This project started as the research how much useful data we can extract from open source remote sensing data (Sentinel-2, Landsat-8, ALOS & Arctic DEM).
          The main challenge was the relative small resolution of the available data (10 - 100 m/px), so some problems like connected road graph detection required developing algorithms different from traditional CNNs.
          At the moment we successfully detect roads, buildings, water objects, wetlands, forests (and their types), estimate biomass volumes and CO2 consumption, detect clouds,  sand spots, and upscale data resolution.
          Solutions for some of the listed problems (on the similar data resolution) are not published in the scientific papers, but where such comparison can be correctly performed - our results are close and sometimes (depending on the region) even higher than the SOTA.  \
          **Algorithms stack:** modern architectures for semantic segmentation (U-net and its variants, FarSeg, Swin transformer U-net) and some self-made architectures. We use ESRGAN, SwinIR and custom architectures for image super-resolution. Also we use CRFs for postprocessing.  \
          **Technology stack:** PyTorch, Shapely, GDAL, PostgreSQL, GeoAlchemy, FastAPI, Docker  \
          Currently we are packing our solutions into QGIS software plugin for our customer.

      - layout: top-middle
        title: General Plan Optimization
        additional_links:
          - title: Habr
            icon: fas fa-book
            url: https://habr.com/ru/company/numdes/blog/599971/
          - title:  NumDes
            icon: fas fa-link
            url: https://numdes.com/
        description: |
          At this project I was developing algorithms for multi-factor optimization of general topology, network of roads and pipes to minimize total construction cost.
          As the result we have provided solution that is more cost and space utilization efficient than the one, which was manualy developed by an expert.  \
          **Algorithms stack:** Bayessian optimization, Dijkstra, SGD  \
          **Technology stack:** PyTorch, Shapely, GDAL, Optuna, PostgreSQL, GeoAlchemy, Graphene, Docker


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
