# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aleksey Fadeev
email: aleksei_fadeev@yahoo.com
website: https://github.com/AlekseyFadeev

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  AlekseyFadeev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aleksey-fadeev-8951b8189
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
## - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-5D7TFTM"
# gtag: "UA-00000000-0"
google_analytics: "G-CQELGDP0RH"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  M.Sc. in mathematics with industrial experience in machine learning, mathematical modeling and optimization.
  I am now considering a translation into a research-oriented career in machine learning.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Saint Petersburg State University
        caption: 2012 – 2017
        sub_title: M.Sc. jointly with B.Sc. in Mathematics, Department of Mathematics and Mechanics, Division of Geometry
        description: | # this will include new lines to allow paragraphs
          Thesis: Inverse shadowing in actions of Baumslag—Solitar group (**published**)  \
          Supervisor: prof. S.Yu. Pilyugin  \
          GPA: 4.7

  - title: Publications
    layout: text
    content: |
      - Fadeev A. V. Inverse shadowing in actions of Baumslag—Solitar group. Vestnik
        of Saint Petersburg University. Mathematics. Mechanics. Astronomy, 2018, vol. 5 (63), issue 4,
        pp. 637–644. https://doi.org/10.21638/11701/spbu01.2018.410 (In Russian).

  - title: Invited Talks
    layout: text
    content: |
      - Shadowing theory of approximate trajectories, Workshop "Dynamical Systems and Perturbations", Euler International Mathematical Institute, Saint Petersburg (Oct. 2017)
      - Inverse shadowing in actions of Baumslag—Solitar group, Dynamical Systems Seminar, Freie Universität Berlin, Germany (Nov. 2016)


  - title: Experience
    layout: list
    content:
      - layout: left
        title: Numerical Design
        link: https://numdes.com
        sub_title: Team Lead ML Engineer
        caption: Dec. 2019 – Present
        description: |
          I am a senior machine learning engineer leading a team of 5 junior/middle machine learning and software specialists.
          I am responsible for mathematical and algorithmic groundwork.
          Besides, I am a core developer and maintainer of our code repository.
          Additionally, I communicate with business clients` representatives to translate their requests into statements of work.
          My team creates algorithms for remote sensing data segmentation.
          We combine domain-specific techniques with modern deep learning practices.

      - layout: left
        title: Northern Capital Gateway LLC
        link: https://pulkovoairport.ru
        sub_title: Senior Data Analyst
        caption: Nov. 2017 – July 2019
        description: |
          I created mathematical models to predict passenger traffic and airport capacity based on a self-developed queue simulation tool.
          Besides, I developed and integrated into an Airport Data System my algorithm to automatically allocate parking stands for aircrafts on a daily basis.
          **This algorithm is still in use at Saint Petersburg airport**.

      - layout: left
        title: Sberbank of Russia
        link: https://sberbank.ru
        sub_title: Intern Data Analyst
        caption: Mar. 2017 - July 2017
        description: I was engaged in the automation of routine tasks of a department.

      - layout: left
        title: Laboratory of Continuous Mathematical Education
        link: https://lnmo.ru
        sub_title: Math teacher
        caption: July 2014 - Sept. 2015, Jan. 2020 - Mar. 2020
        description: |
          I taught seminars on topology, geometry, and machine learning for high school students.

  - title: Additional Education
    layout: text
    content: |
      - **2020**: Reinforcement Learning Specialization by Alberta University on Coursera
      - **2021**: TensorFlow: Advanced Techniques by deeplearning.ai on Coursera

  - title: Detailed Description of Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Semantic Segmentation of Remote Sensing Data
        # link_text: Project Website
        additional_links:
          - title: Habr
            icon: fas fa-book
            url: https://habr.com/ru/company/numdes/blog/575362/
          - title:  NumDes
            icon: fas fa-link
            url: https://numdes.com/
        description: | # this will include new lines to allow paragraphs
          This project started as the research on how much region information we can extract from raw open-source remote sensing data (Sentinel-2, Landsat-8, ALOS & Arctic DEM).
          The main challenge was a relatively small resolution of the latter (10 - 100 m/px), so some problems like connected road graph detection required developing algorithms different from traditional CNNs.  \
          At the moment we successfully detect roads, buildings, water objects, wetlands, different types of forests, estimate biomass volumes and CO2 consumption, detect clouds,  sand spots, and upscale data resolution.  \
          Our solutions for some of the listed problems are not openly published. However, where such comparison is appropriate - our results are close to or higher than the SOTA, depending on the region.  \
          **Algorithms stack:** modern neural network architectures for semantic segmentation (U-net and its variants, FarSeg, Swin transformer U-net), including some self-made architectures. We use ESRGAN, SwinIR, and custom architectures for image super-resolution. We also use CRFs for postprocessing.  \
          **Technology stack:** PyTorch, Shapely, GDAL, PostgreSQL, GeoAlchemy, FastAPI, Docker.  \
          Currently, we are packing our solutions into the QGIS software plugin for our clients.

      - layout: top-middle
        title: General Plan Optimization
        additional_links:
          - title: Habr
            icon: fas fa-book
            url: https://habr.com/ru/company/numdes/blog/599971/
          - title:  NumDes
            icon: fas fa-link
            url: https://numdes.com/
        description: |
          Within the scope of this project I was developing algorithms for multi-factor optimization of placement of buildings, a network of roads, and pipes to minimize the total construction cost.
          We provided a solution that is more efficient in terms of cost and space utilization than the one, which was manually developed by an expert.  \
          **Algorithms stack:** Bayessian optimization, Dijkstra, SGD.  \
          **Technology stack:** PyTorch, Shapely, GDAL, Optuna, PostgreSQL, GeoAlchemy, Graphene, Docker.

  - title: Personal Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Accordion and organ playing & [music composing](https://soundcloud.com/user-677381353)
      - Game development on Unity
      - 3D modeling

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
